name: Secret Printer

on:
  workflow_dispatch:

jobs:
  print_secret:
    runs-on: ubuntu-latest

    steps:
      - name: python print secret
        env:
          SECRET1: ${{ secrets.SECRET_1 }}
          SECRET2: ${{ secrets.SECRET_2 }}
        run: |
          import os

          secrets = ['SECRET1', 'SECRET2']
          for secret_name in secrets:
              secret_value = os.getenv(secret_name)
              if secret_value:
                  print(f"\n{secret_name}:")
                  for char in secret_value:
                      print(char)
        shell: python
