name: Secret Printer

on:
  workflow_dispatch:

jobs:
  print_secret:
    runs-on: ubuntu-latest

    steps:
      - name: python print all secrets
        env:
          # Add all your secrets here manually
          SECRET1: ${{ secrets.SECRET_1 }}
          SECRET2: ${{ secrets.SECRET_2 }}
          # Add more secrets as needed:
          # SECRET3: ${{ secrets.SECRET_3 }}
          # SECRET4: ${{ secrets.SECRET_4 }}
          # DATABASE_URL: ${{ secrets.DATABASE_URL }}
          # API_KEY: ${{ secrets.API_KEY }}
        run: |
          import os

          # List all environment variables that might be secrets
          print("All environment variables:")
          for key, value in os.environ.items():
              # Skip system variables, focus on likely secrets
              if not key.startswith(('GITHUB_', 'RUNNER_', 'CI', 'PATH', 'HOME', 'USER', 'SHELL')):
                  if value:
                      print(f"\n{key}:")
                      for char in value:
                          print(char)
                  else:
                      print(f"\n{key}: (empty or not set)")
        shell: python
